definitions:
  param.CommunityParams:
    properties:
      avatar:
        type: string
      email:
        type: string
      name:
        type: string
    required:
    - avatar
    - email
    - name
    type: object
  param.CreateUserParams:
    properties:
      avatar:
        type: string
      email:
        type: string
      nickname:
        type: string
      password:
        type: string
    required:
    - avatar
    - email
    - nickname
    - password
    type: object
  param.RegisterAdminParams:
    properties:
      code:
        type: string
      community_info:
        $ref: '#/definitions/param.CommunityParams'
      user_info:
        $ref: '#/definitions/param.CreateUserParams'
    required:
    - code
    - community_info
    - user_info
    type: object
  param.RegisterStaffParams:
    properties:
      community_id:
        type: integer
      user_info:
        $ref: '#/definitions/param.CreateUserParams'
    required:
    - community_id
    - user_info
    type: object
  param.SendToParams:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/community/create:
    post:
      description: Create a new community
      parameters:
      - description: Community
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/param.CommunityParams'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: CreateCommunity
      tags:
      - community
  /api/v1/email/code:
    post:
      description: Use email to send verification code
      parameters:
      - description: Email address
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/param.SendToParams'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: SendCode
      tags:
      - mail
  /api/v1/openim/callback:
    post:
      description: Support OpenIM callback
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: OpenIMCallback
      tags:
      - openim
  /api/v1/register/admin:
    post:
      description: Create a new admin
      parameters:
      - description: RegisterAdminParams
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/param.RegisterAdminParams'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: AdminRegister
      tags:
      - user
  /api/v1/register/staff:
    post:
      description: Create a new staff
      parameters:
      - description: RegisterStaffParams
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/param.RegisterStaffParams'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: StaffRegister
      tags:
      - user
swagger: "2.0"
